### ISSUE TITLE
Does not work with Django 1.6 out of the box

### ISSUE THREAD

**Issue by cyberjoac** [sigurdga/django-jquery-file-upload#55]
This is the error message I get when trying to syncdb and runserver.
ImportError: cannot import name execute_manager

Explanation of the error here:
http://stackoverflow.com/questions/20906305/import-error-cannot-import-name-execute-manager-in-windows-environment

**Comment by sigurdga** [comment]
I'm closing old issues that should be fixed by now. I'm sorry I couldn't help you back then. This example is as of today compatible with Django 1.9.
